### ISSUE TITLE
Formatting Data for Custom Task

### ISSUE THREAD

**Issue by avhirupc** [microsoft/MT-DNN#4]
Hi,

I have two classifications tasks, one with 1000 classes and another with 100. I wish to train a model on both of these tasks.
I understand defining the task params, as you specified in the classification example notebook.
Though I do not understand, how do I format my datasets? Could you help me with that?

Upon looking closely in sample data, I can see :
uid: a unique identifier
token: list of tokens ( how do I generate this, should I use bert tokenizer to generate these)
label: label string
type: I don't understand what this is?(is this the positional encoding in bert)

Thanks

**Comment by awaemmanuel** [comment]
@namisan can you comment on this please

**Comment by avhirupc** [comment]
Cool . I will try it out. Thanks @namisan
